services:
  - type: web
    name: badanti-matcher
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: badanti-data
      mountPath: /opt/render/project/src
      sizeGB: 1
